"""Add unique constraint to document_metadata

Revision ID: 16740b770ba5
Revises: 668b84aa0951
Create Date: 2026-09-16 12:47:00.766554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16740b770ba5'
down_revision: Union[str, Sequence[str], None] = '668b84aa0951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_metadata_version', 'document_metadata', ['document_id', 'version_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_metadata_version', 'document_metadata', type_='unique')
    # ### end Alembic commands ###
