"""add stage history sequence

Revision ID: cbe3e0a90169
Revises: 16740b770ba5
Create Date: 2026-09-17 22:52:14.159946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe3e0a90169'
down_revision: Union[str, Sequence[str], None] = '16740b770ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_stage_history', sa.Column('sequence', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_stage_history', 'sequence')
    # ### end Alembic commands ###
